networks:
  common-network:

services:

  mysql:
    container_name: mysql
    image: mysql:oraclelinux8
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    healthcheck:
      test: mysqladmin ping -h localhost --password=password
      timeout: 20s
      retries: 10
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - common-network
  
  taobench:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - common-network
